### ISSUE TITLE
Saving the decrypted File 

### ISSUE THREAD

**Issue by DreDondada** [NEORIS-ZDEVOPS/DS-Editor#3]
Hello,

Nice Editor. I installed the DS Editor on VS Studio Code. However, having decrypted the EBCDIC File how can i save the entire file.

Moreso, is there an API that i can call to decrypt an entire file?

Regards
Dare

**Comment by antonkc** [comment]
Greetings,

Sequentials datasets opened with "Open with DS Editor" are downloaded to a local path in your computer. You can find them if you right click the document tab. Refer to the image bellow.
![image](https://github.com/NEORIS-ZDEVOPS/DS-Editor/assets/31370603/b571c6bd-e4ca-4167-b759-e70a3fa5d8c5)

Saving the document will write the changes to this file.

Regarding the decrypting api, right now that functionality is not present. The editor will always save to the native mainframe codification. We did not implement this due to ZOWE Explorer extension already having an option to download the sequential datasets as text. Refer to the image bellow.
![image](https://github.com/NEORIS-ZDEVOPS/DS-Editor/assets/31370603/ebb21724-be6f-4568-9a6e-e1f4badebb54)

Are you perhaps suggesting being able the export the table format? We will take note of that regardless of your answer.

I will be around if you have any more questions.

**Comment by DreDondada** [comment]
Thanks for the response. I installed in on Windows, i am working on a Project to decrypt a Mastercard File and convert to Excel.

**Comment by DreDondada** [comment]
Am not connecting to Mainframe. The File has already been downloaded to a path on my Windows 11 computer. All i want is decrypt and save in Excel

**Comment by antonkc** [comment]
I understand. Sadly, no single button to do that is implemented. The closest thing achievable right now through our extension is using [Ctrl]+[A], [Ctrl]+[C] and then pasting the clipboard to a excel file or text file (former is untested). Also, you can change the rows per page as much as you wish. Refer bellow.
![image](https://github.com/NEORIS-ZDEVOPS/DS-Editor/assets/31370603/5da58678-2e6e-46bc-b3e7-37d6f7b7c430)

Hope it helps.

We will take note of this use case for the future.

**Comment by DreDondada** [comment]
Ok Thanks.
[290823_IPM_OUT_GCMS_F.zip](https://github.com/NEORIS-ZDEVOPS/DS-Editor/files/14372809/290823_IPM_OUT_GCMS_F.zip)

i attached the file am trying to decrypt

**Comment by antonkc** [comment]
If I understood right, you shouldn't be posting THAT file here.

**Comment by DreDondada** [comment]
oh ok. Apologies.
Let me retrieve it

**Comment by antonkc** [comment]
The potetial problem is saw is that that file can be accessed by anyone, it is public. Rarely anything related with credit cards should be published that lightly. If you do, you should argue the reasons why publishing such a file will not harmful in any way.

You may refer to me by mail for such things, and the file should by protected by password. And honestly, you shouldn't believe in me neither. I am just a extension developer.

**Comment by DreDondada** [comment]
Yeah, I understand. maybe i was too eager to get it resolved.

**Comment by antonkc** [comment]
Give me something to contact you directly. aka, a mail.

**Comment by DreDondada** [comment]
dare.adeniyi@gmail.com.

**Comment by antonkc** [comment]
Although our extension offered some capabilities that enabled in a way to help this use-case, I understood that the real problem was that "Reopen with ecoding..." didn't feature an option that allowed the user to read the file as plain text. The file wasn't a sequential dataset. This doesn't fall into the scope of this extension.

I did guide the user on how to use DS Editor to extrart legible text to a text editor, but I am sure there should be other ways of doing so more effectively without our extension.

However, we did take note of an improvement to me made: Export to text or csv. We do not have this functionality and it may have legitimate use-cases.
